# Tennis Data Observation & Exploration
Jupyter Notebook used to observe, clean, explore and find insight about the data. This information are going to be used to develop different Python Modules used to make the Tennis Momentum Engine.

#### 1. Setup & Imports

In [147]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import os

plt.style.use('ggplot')
sns.set_theme(style="whitegrid")
%matplotlib inline

#### 2. Data Loading

In [148]:
RAW_DATA_PATH = "../data/raw_matches.csv"
if not os.path.exists(RAW_DATA_PATH):
  raise FileNotFoundError(f"Run data_retrieval.py first → {RAW_DATA_PATH}")
df = pd.read_csv(RAW_DATA_PATH, low_memory=False)

print(f"Dataset contains {df.shape[0]} matches and {df.shape[1]} features.")
display(df.head())

Dataset contains 79019 matches and 50 features.

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year
0,2000-301,Auckland,Hard,32,A,20000110,1,103163,1.0,NaN,...,39.0,29.0,17.0,4.0,7.0,11.0,1612.0,63.0,595.0,2000
1,2000-301,Auckland,Hard,32,A,20000110,2,102607,NaN,Q,...,25.0,18.0,12.0,3.0,6.0,211.0,157.0,49.0,723.0,2000
2,2000-301,Auckland,Hard,32,A,20000110,3,103252,NaN,NaN,...,20.0,7.0,8.0,7.0,11.0,48.0,726.0,59.0,649.0,2000
3,2000-301,Auckland,Hard,32,A,20000110,4,103507,7.0,NaN,...,29.0,14.0,10.0,6.0,8.0,45.0,768.0,61.0,616.0,2000
4,2000-301,Auckland,Hard,32,A,20000110,5,102103,NaN,Q,...,34.0,18.0,12.0,5.0,9.0,167.0,219.0,34.0,873.0,2000

#### 3. Data Exploration

In [149]:
print(f"Data Shape: {df.shape}", end="\n\n")
print(df.info())

Data Shape: (79019, 50)

<class 'pandas.DataFrame'>
RangeIndex: 79019 entries, 0 to 79018
Data columns (total 50 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   tourney_id          79019 non-null  str
 1   tourney_name        79019 non-null  str
 2   surface             78966 non-null  str
 3   draw_size           79019 non-null  int64
 4   tourney_level       79019 non-null  str
 5   tourney_date        79019 non-null  int64
 6   match_num           79019 non-null  int64
 7   winner_id           79019 non-null  int64
 8   winner_seed         32861 non-null  float64
 9   winner_entry        10153 non-null  str
 10  winner_name         79019 non-null  str
 11  winner_hand         79019 non-null  str
 12  winner_ht           77485 non-null  float64
 13  winner_ioc          79019 non-null  str
 14  winner_age          79007 non-null  float64
 15  loser_id            79019 non-null  int64
 16  loser_seed          18257 non-null  float64
 17  loser_entry         16397 non-null  str
 18  loser_name          79019 non-null  str
 19  loser_hand          79015 non-null  str
 20  loser_ht            75941 non-null  float64
 21  loser_ioc           79019 non-null  str
 22  loser_age           79005 non-null  float64
 23  score               79019 non-null  str
 24  best_of             79019 non-null  int64
 25  round               79019 non-null  str
 26  minutes             70312 non-null  float64
 27  w_ace               72109 non-null  float64
 28  w_df                72109 non-null  float64
 29  w_svpt              72109 non-null  float64
 30  w_1stIn             72109 non-null  float64
 31  w_1stWon            72109 non-null  float64
 32  w_2ndWon            72109 non-null  float64
 33  w_SvGms             72109 non-null  float64
 34  w_bpSaved           72109 non-null  float64
 35  w_bpFaced           72109 non-null  float64
 36  l_ace               72109 non-null  float64
 37  l_df                72109 non-null  float64
 38  l_svpt              72109 non-null  float64
 39  l_1stIn             72109 non-null  float64
 40  l_1stWon            72109 non-null  float64
 41  l_2ndWon            72109 non-null  float64
 42  l_SvGms             72109 non-null  float64
 43  l_bpSaved           72109 non-null  float64
 44  l_bpFaced           72109 non-null  float64
 45  winner_rank         78420 non-null  float64
 46  winner_rank_points  78420 non-null  float64
 47  loser_rank          77466 non-null  float64
 48  loser_rank_points   77466 non-null  float64
 49  year                79019 non-null  int64
dtypes: float64(29), int64(7), str(14)
memory usage: 36.0 MB
None

In [150]:
df.describe()

,draw_size,tourney_date,match_num,winner_id,winner_seed,winner_ht,winner_age,loser_id,loser_seed,loser_ht,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year
count,79019.000000,7.901900e+04,79019.000000,79019.000000,32861.000000,77485.000000,79007.000000,79019.000000,18257.000000,75941.000000,...,72109.000000,72109.000000,72109.000000,72109.00000,72109.000000,78420.000000,78420.000000,77466.000000,77466.000000,79019.000000
mean,55.533024,2.012267e+07,112.454726,114063.385907,7.460242,186.341795,26.292793,113909.447209,9.014789,185.728263,...,32.552816,14.899167,12.307964,4.76028,8.570276,80.029712,1625.590691,117.532375,988.824813,2012.218125
std,40.407124,7.684293e+04,139.327826,27507.648427,6.873754,7.029637,3.989053,27193.731024,7.455624,6.981291,...,14.359979,7.171966,4.217732,3.26255,4.135239,140.577272,2022.009382,186.471030,1132.567070,7.684083
min,2.000000,2.000010e+07,1.000000,100644.000000,1.000000,3.000000,14.900000,100644.000000,1.000000,3.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,1.000000,1.000000,1.000000,1.000000,2000.000000
25%,32.000000,2.006010e+07,12.000000,103602.000000,3.000000,183.000000,23.400000,103565.000000,4.000000,183.000000,...,22.000000,10.000000,9.000000,2.00000,6.000000,18.000000,582.000000,36.000000,436.000000,2006.000000
50%,32.000000,2.012042e+07,32.000000,104547.000000,5.000000,185.000000,26.100000,104561.000000,7.000000,185.000000,...,30.000000,14.000000,11.000000,4.00000,8.000000,45.000000,948.000000,68.000000,716.000000,2012.000000
75%,64.000000,2.019020e+07,262.000000,105777.000000,9.000000,190.000000,28.900000,105916.000000,12.000000,190.000000,...,40.000000,19.000000,15.000000,7.00000,11.000000,86.000000,1755.000000,114.000000,1117.000000,2019.000000
max,128.000000,2.026042e+07,1701.000000,214419.000000,35.000000,211.000000,46.000000,214425.000000,35.000000,211.000000,...,284.000000,101.000000,91.000000,27.00000,38.000000,2101.000000,16950.000000,2173.000000,16950.000000,2026.000000

In [151]:
tourney_level_values = df["tourney_level"].unique().tolist()
surface_values = df["surface"].unique().tolist()
draw_size_values = df["draw_size"].unique().tolist()
round_values = df["round"].unique().tolist()
winner_entry_values = df["winner_entry"].unique().tolist()
winner_hand_values = df["winner_hand"].unique().tolist()

print(f"Unique values for 'TOURNEY_LEVEL': ({len(tourney_level_values)}, {tourney_level_values})")
print(f"Unique values for 'SURFACE': ({len(surface_values)}, {surface_values})")
print(f"Unique values for 'DRAW_SIZE': ({len(draw_size_values)}, {draw_size_values})")
print(f"Unique values for 'ROUND': ({len(round_values)}, {round_values})")
print(f"Unique values for 'WINNER_ENTRY': ({len(winner_entry_values)}, {winner_entry_values})")
print(f"Unique values for 'WINNER_HAND': ({len(winner_hand_values)}, {winner_hand_values})")

Unique values for 'TOURNEY_LEVEL': (6, ['A', 'M', 'G', 'F', 'D', 'O'])
Unique values for 'SURFACE': (5, ['Hard', 'Clay', 'Grass', 'Carpet', nan])
Unique values for 'DRAW_SIZE': (14, [32, 56, 48, 96, 64, 128, 8, 4, 28, 16, 24, 12, 2, 18])
Unique values for 'ROUND': (10, ['R32', 'R16', 'QF', 'SF', 'F', 'R64', 'R128', 'RR', 'BR', 'ER'])
Unique values for 'WINNER_ENTRY': (12, [nan, 'Q', 'WC', 'LL', 'PR', 'SE', 'ALT', 'Alt', 'UP', 'ITF', 'W', 'NG'])
Unique values for 'WINNER_HAND': (4, ['R', 'L', 'U', 'A'])

In [152]:
missing = df.isnull().sum().sort_values(ascending=False)
missing[missing > 0]

winner_entry          68866
loser_entry           62622
loser_seed            60762
winner_seed           46158
minutes                8707
l_ace                  6910
l_svpt                 6910
l_1stIn                6910
l_1stWon               6910
l_df                   6910
w_1stIn                6910
w_ace                  6910
w_df                   6910
w_svpt                 6910
w_2ndWon               6910
w_1stWon               6910
w_SvGms                6910
l_2ndWon               6910
l_SvGms                6910
l_bpSaved              6910
l_bpFaced              6910
w_bpSaved              6910
w_bpFaced              6910
loser_ht               3078
loser_rank_points      1553
loser_rank             1553
winner_ht              1534
winner_rank_points      599
winner_rank             599
surface                  53
loser_age                14
winner_age               12
loser_hand                4
dtype: int64

#### 4. Data Cleaning
- 4.1 Removing walkovers, unfinished matches, defaulted matches, missing score matches
- 4.2 Handle missing values and datatypes

In [153]:
invalid_tokens = r"W/O|RET|DEF|ABD|UNF|NAN"
numeric_cols = ["w_ace", "w_df", "w_svpt", "w_1stIn", "w_1stWon", "w_2ndWon", "w_bpSaved", "w_bpFaced", "w_SvGms",
            "l_ace", "l_df", "l_svpt", "l_1stIn", "l_1stWon", "l_2ndWon", "l_bpSaved", "l_bpFaced", "l_SvGms",
            "winner_rank", "winner_rank_points", "loser_rank_points", "loser_rank",
            "winner_age", "winner_ht", "loser_age", "loser_ht", 
            "best_of"
]

# Filter out matches with no score
df = df[df["score"].notna()]
# Filter out retirements, walkovers, defaults (stats are skewed/incomplete)
df = df[~df["score"].str.contains(invalid_tokens, case=False, na=False)].copy()
# Handle missing `surface` value
df["surface"] = df["surface"].fillna("Unknown")
# Convert all the numeric columns to numeric
for col in numeric_cols:
  df[col] = pd.to_numeric(df[col], errors="coerce")
# Convert dates 
df["tourney_date"] = pd.to_datetime(df["tourney_date"], format="%Y%m%d")

df.info()

<class 'pandas.DataFrame'>
Index: 76225 entries, 0 to 79018
Data columns (total 50 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   tourney_id          76225 non-null  str
 1   tourney_name        76225 non-null  str
 2   surface             76225 non-null  str
 3   draw_size           76225 non-null  int64
 4   tourney_level       76225 non-null  str
 5   tourney_date        76225 non-null  datetime64[us]
 6   match_num           76225 non-null  int64
 7   winner_id           76225 non-null  int64
 8   winner_seed         31833 non-null  float64
 9   winner_entry        9729 non-null   str
 10  winner_name         76225 non-null  str
 11  winner_hand         76225 non-null  str
 12  winner_ht           74762 non-null  float64
 13  winner_ioc          76225 non-null  str
 14  winner_age          76213 non-null  float64
 15  loser_id            76225 non-null  int64
 16  loser_seed          17389 non-null  float64
 17  loser_entry         16050 non-null  str
 18  loser_name          76225 non-null  str
 19  loser_hand          76221 non-null  str
 20  loser_ht            73222 non-null  float64
 21  loser_ioc           76225 non-null  str
 22  loser_age           76211 non-null  float64
 23  score               76225 non-null  str
 24  best_of             76225 non-null  int64
 25  round               76225 non-null  str
 26  minutes             68110 non-null  float64
 27  w_ace               69882 non-null  float64
 28  w_df                69882 non-null  float64
 29  w_svpt              69882 non-null  float64
 30  w_1stIn             69882 non-null  float64
 31  w_1stWon            69882 non-null  float64
 32  w_2ndWon            69882 non-null  float64
 33  w_SvGms             69881 non-null  float64
 34  w_bpSaved           69882 non-null  float64
 35  w_bpFaced           69882 non-null  float64
 36  l_ace               69882 non-null  float64
 37  l_df                69882 non-null  float64
 38  l_svpt              69882 non-null  float64
 39  l_1stIn             69882 non-null  float64
 40  l_1stWon            69882 non-null  float64
 41  l_2ndWon            69882 non-null  float64
 42  l_SvGms             69881 non-null  float64
 43  l_bpSaved           69882 non-null  float64
 44  l_bpFaced           69882 non-null  float64
 45  winner_rank         75657 non-null  float64
 46  winner_rank_points  75657 non-null  float64
 47  loser_rank          74724 non-null  float64
 48  loser_rank_points   74724 non-null  float64
 49  year                76225 non-null  int64
dtypes: datetime64[us](1), float64(29), int64(6), str(14)
memory usage: 35.4 MB

#### 5. Feature Engineering
For each match we compute:
  - Serve rates for winner and loser (ace %, df %, 1st serve %, etc.)
  - Breakpoints Save & Conversion rates (bp saved %, bp conversion %)
  - Return points won (= 1 - opponent serve points won)
  - Delta features (winner minus loser)
  - Context features (surface one-hot, tournament level one-hot, best-of binary feature)
  - Binary feature "came_back" and "upset"

Define also a Player Profile for each player as a new dataset.

In [154]:
def g(prefix: str, col: str) -> str:
      return prefix+col

In [155]:
# Binary Features: Comeback
cleaned_scores = df["score"].str.replace(r"\(\d+\)", "", regex=True)
first_sets = cleaned_scores.str.split().str[0]
set_split = first_sets.str.split("-", expand=True)
w_s1_games = pd.to_numeric(set_split[0], errors="coerce")
l_s1_games = pd.to_numeric(set_split[1], errors="coerce")
df["came_back"] = (w_s1_games < l_s1_games).astype(int)

df[["score", "came_back"]].head(5)

            score  came_back
0     7-5 4-6 7-5          0
1         7-5 7-5          0
2         6-3 6-1          0
3         6-4 6-4          0
4  0-6 7-6(7) 6-1          1

In [156]:
# Binary Features: Upset
df["upset"] = np.where(df["winner_rank"] > df["loser_rank"], 1, 0)

df[["winner_rank", "loser_rank", "upset"]].head(5)
df["winner_rank"].isnull().sum()

np.int64(568)

In [157]:
# Features: Winner & Loser Serve %
new_serve_features = ["ace_rate", "df_rate", "1stIn_pct", "1stWon_pct", "2ndWon_pct", "srvWon_pct"]

df["w_ace_rate"] = df["w_ace"] / df["w_svpt"]
df["w_df_rate"] = df["w_df"] / df["w_svpt"]
df["w_1stIn_pct"] = df["w_1stIn"] / df["w_svpt"]
df["w_1stWon_pct"] = df["w_1stWon"] / df["w_1stIn"]
df["w_2ndWon_pct"] = df["w_2ndWon"] / (df["w_svpt"] - df["w_1stIn"]) 
df["w_srvWon_pct"] = (df["w_1stWon"] + df["w_2ndWon"]) / df["w_svpt"]

df["l_ace_rate"] = df["l_ace"] / df["l_svpt"]
df["l_df_rate"] = df["l_df"] / df["l_svpt"]
df["l_1stIn_pct"] = df["l_1stIn"] / df["l_svpt"]
df["l_1stWon_pct"] = df["l_1stWon"] / df["l_1stIn"]
df["l_2ndWon_pct"] = df["l_2ndWon"] / (df["l_svpt"] - df["l_1stIn"]) 
df["l_srvWon_pct"] = (df["l_1stWon"] + df["l_2ndWon"]) / df["l_svpt"]

full_serve_features = [g("w_",f) for f in new_serve_features] + [g("l_", f) for f in new_serve_features]
df[full_serve_features].head(5)
# df[[g("w_", f) for f in new_serve_features]].isnull().sum()

,w_ace_rate,w_df_rate,w_1stIn_pct,w_1stWon_pct,w_2ndWon_pct,w_srvWon_pct,l_ace_rate,l_df_rate,l_1stIn_pct,l_1stWon_pct,l_2ndWon_pct,l_srvWon_pct
0,0.187500,0.041667,0.510417,0.795918,0.595745,0.697917,0.066038,0.075472,0.518868,0.709091,0.568627,0.641509
1,0.065789,0.039474,0.684211,0.750000,0.541667,0.684211,0.067568,0.135135,0.432432,0.781250,0.428571,0.581081
2,0.000000,0.000000,0.636364,0.714286,0.600000,0.672727,0.000000,0.107143,0.589286,0.606061,0.304348,0.482143
3,0.094340,0.018868,0.528302,0.928571,0.600000,0.773585,0.157143,0.028571,0.614286,0.674419,0.518519,0.614286
4,0.010204,0.020408,0.673469,0.590909,0.437500,0.540816,0.086957,0.086957,0.500000,0.739130,0.391304,0.565217

In [158]:
# Features: Breakpoints Stats %
new_breakpoints_features = ["bpSaved_pct", "bpConversion_pct"]

df["w_bpSaved_pct"] = df["w_bpSaved"] / df["w_bpFaced"]
df["l_bpSaved_pct"] = df["l_bpSaved"] / df["l_bpFaced"]
df["w_bpConversion_pct"] = 1 - df["l_bpSaved_pct"] 
df["l_bpConversion_pct"] = 1 - df["w_bpSaved_pct"]

full_breakpoints_features = [g("w_",f) for f in new_breakpoints_features] + [g("l_", f) for f in new_breakpoints_features]
df[full_breakpoints_features].head(5)
# df[[g("w_", f) for f in new_breakpoints_features]].isnull().sum()

   w_bpSaved_pct  w_bpConversion_pct  l_bpSaved_pct  l_bpConversion_pct
0       0.600000            0.428571       0.571429            0.400000
1       0.833333            0.500000       0.500000            0.166667
2       1.000000            0.363636       0.636364            0.000000
3            NaN            0.250000       0.750000                 NaN
4       0.545455            0.444444       0.555556            0.454545

In [104]:
# Features: Return Points Won %
df["w_retWon_pct"] = 1 - df["l_srvWon_pct"] 
df["l_retWon_pct"] = 1 - df["w_srvWon_pct"]
df[["l_srvWon_pct", "w_retWon_pct", "w_srvWon_pct", "l_retWon_pct"]].head(5)

   l_srvWon_pct  w_retWon_pct  w_srvWon_pct  l_retWon_pct
0      0.641509      0.358491      0.697917      0.302083
1      0.581081      0.418919      0.684211      0.315789
2      0.482143      0.517857      0.672727      0.327273
3      0.614286      0.385714      0.773585      0.226415
4      0.565217      0.434783      0.540816      0.459184

In [103]:
# Feature: Ranking Gap
df["rank_gap"] = df["winner_rank"] - df["loser_rank"]
df[["winner_rank", "loser_rank", "rank_gap"]].head(5)

   winner_rank  loser_rank  rank_gap
0         11.0        63.0     -52.0
1        211.0        49.0     162.0
2         48.0        59.0     -11.0
3         45.0        61.0     -16.0
4        167.0        34.0     133.0

In [ ]:
# Features: Delta Features
df["delta_ace_pct"] = df["w_ace_rate"] - df["l_ace_rate"]
df["delta_1stWon_pct"] = df["w_1stWon_pct"] - df["l_1stWon_pct"]
df["delta_bpSaved_pct"] = df["w_bpSaved_pct"] - df["l_bpSaved_pct"]
df["delta_srvWon_pct"] = df["w_srvWon_pct"] - df["l_srvWon_pct"]
df["delta_retWon_pct"] = df["w_retWon_pct"] - df["l_retWon_pct"]

In [109]:
# Features: Binary One-Hot Features (Context)
df = df.assign(
  surf_hard = (df["surface"] == "Hard").astype(int),
  surf_clay = (df["surface"] == "Clay").astype(int),
  surf_grass = (df["surface"] == "Grass").astype(int),
  surf_carpet = (df["surface"] == "Carpet").astype(int),
  
  is_gs = (df["tourney_level"] == "G").astype(int),
  is_masters = (df["tourney_level"] == "M").astype(int),
  is_atp = (df["tourney_level"] == "A").astype(int),
  is_finals = (df["tourney_level"] == "F").astype(int),
  is_davis = (df["tourney_level"] == "D").astype(int),
  
  best_of_5 = (df["best_of"] == 5).astype(int)
)

In [ ]:
df = df.replace([np.inf, -np.inf], np.nan)
df = df.dropna(subset=["w_ace_rate", "l_ace_rate", "came_back"])
df = df.drop(columns=["surface", "draw_size", "tourney_level", "match_num", "best_of", "round",
                        "winner_seed", "winner_entry", "winner_ioc", "winner_rank_points",
                        "loser_seed", "loser_entry", "loser_ioc", "loser_rank_points"])
df = df.reset_index(drop=True)

,tourney_id,tourney_name,tourney_date,winner_id,winner_name,winner_hand,winner_ht,winner_age,loser_id,loser_name,...,surf_hard,surf_clay,surf_grass,surf_carpet,is_gs,is_masters,is_atp,is_finals,is_davis,best_of_5
0,2000-301,Auckland,2000-01-10,103163,Tommy Haas,R,188.0,21.7,101543,Jeff Tarango,...,1,0,0,0,0,0,1,0,0,0
1,2000-301,Auckland,2000-01-10,102607,Juan Balcells,R,190.0,24.5,102644,Franco Squillari,...,1,0,0,0,0,0,1,0,0,0
2,2000-301,Auckland,2000-01-10,103252,Alberto Martin,R,175.0,21.3,102238,Alberto Berasategui,...,1,0,0,0,0,0,1,0,0,0
3,2000-301,Auckland,2000-01-10,103507,Juan Carlos Ferrero,R,183.0,19.9,103819,Roger Federer,...,1,0,0,0,0,0,1,0,0,0
4,2000-301,Auckland,2000-01-10,102103,Michael Sell,R,180.0,27.3,102765,Nicolas Escude,...,1,0,0,0,0,0,1,0,0,0

In [117]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 69878 entries, 0 to 69877
Data columns (total 67 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   tourney_id          69878 non-null  str
 1   tourney_name        69878 non-null  str
 2   tourney_date        69878 non-null  datetime64[us]
 3   winner_id           69878 non-null  int64
 4   winner_name         69878 non-null  str
 5   winner_hand         69878 non-null  str
 6   winner_ht           69712 non-null  float64
 7   winner_age          69877 non-null  float64
 8   loser_id            69878 non-null  int64
 9   loser_name          69878 non-null  str
 10  loser_hand          69878 non-null  str
 11  loser_ht            69215 non-null  float64
 12  loser_age           69877 non-null  float64
 13  score               69878 non-null  str
 14  minutes             68097 non-null  float64
 15  w_ace               69878 non-null  float64
 16  w_df                69878 non-null  float64
 17  w_svpt              69878 non-null  float64
 18  w_1stIn             69878 non-null  float64
 19  w_1stWon            69878 non-null  float64
 20  w_2ndWon            69878 non-null  float64
 21  w_SvGms             69877 non-null  float64
 22  w_bpSaved           69878 non-null  float64
 23  w_bpFaced           69878 non-null  float64
 24  l_ace               69878 non-null  float64
 25  l_df                69878 non-null  float64
 26  l_svpt              69878 non-null  float64
 27  l_1stIn             69878 non-null  float64
 28  l_1stWon            69878 non-null  float64
 29  l_2ndWon            69878 non-null  float64
 30  l_SvGms             69877 non-null  float64
 31  l_bpSaved           69878 non-null  float64
 32  l_bpFaced           69878 non-null  float64
 33  winner_rank         69771 non-null  float64
 34  loser_rank          69539 non-null  float64
 35  year                69878 non-null  int64
 36  came_back           69878 non-null  int64
 37  upset               69878 non-null  int64
 38  w_ace_rate          69878 non-null  float64
 39  w_df_rate           69878 non-null  float64
 40  w_1stIn_pct         69878 non-null  float64
 41  w_1stWon_pct        69878 non-null  float64
 42  w_2ndWon_pct        69875 non-null  float64
 43  w_srvWon_pct        69878 non-null  float64
 44  l_ace_rate          69878 non-null  float64
 45  l_df_rate           69878 non-null  float64
 46  l_1stIn_pct         69878 non-null  float64
 47  l_1stWon_pct        69878 non-null  float64
 48  l_2ndWon_pct        69875 non-null  float64
 49  l_srvWon_pct        69878 non-null  float64
 50  w_bpSaved_pct       63449 non-null  float64
 51  l_bpSaved_pct       69758 non-null  float64
 52  w_bpConversion_pct  69758 non-null  float64
 53  l_bpConversion_pct  63449 non-null  float64
 54  w_retWon_pct        69878 non-null  float64
 55  l_retWon_pct        69878 non-null  float64
 56  rank_gap            69454 non-null  float64
 57  surf_hard           69878 non-null  int64
 58  surf_clay           69878 non-null  int64
 59  surf_grass          69878 non-null  int64
 60  surf_carpet         69878 non-null  int64
 61  is_gs               69878 non-null  int64
 62  is_masters          69878 non-null  int64
 63  is_atp              69878 non-null  int64
 64  is_finals           69878 non-null  int64
 65  is_davis            69878 non-null  int64
 66  best_of_5           69878 non-null  int64
dtypes: datetime64[us](1), float64(44), int64(15), str(7)
memory usage: 39.8 MB

##### Define Player Profiles

In [125]:
SERVE_COLS = ["ace", "df", "svpt", "1stIn", "1stWon", "2ndWon", "bpSaved", "bpFaced"] # prefix: "w_"=winner, "l_"=loser
w_serve_cols = [g("w_", col) for col in SERVE_COLS]
l_serve_cols = [g("l_", col) for col in SERVE_COLS]

# Create a Winners & Losers slices
winners = df[["winner_name"] + w_serve_cols + ["came_back"]].copy()
# winners.columns = ["player", "ace", "svpt", "came_back"]
winners["is_winner"] = 1
winners.head(5)

,winner_name,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_bpSaved,w_bpFaced,came_back,is_winner
0,Tommy Haas,18.0,4.0,96.0,49.0,39.0,28.0,3.0,5.0,0,1
1,Juan Balcells,5.0,3.0,76.0,52.0,39.0,13.0,5.0,6.0,0,1
2,Alberto Martin,0.0,0.0,55.0,35.0,25.0,12.0,1.0,1.0,0,1
3,Juan Carlos Ferrero,5.0,1.0,53.0,28.0,26.0,15.0,0.0,0.0,0,1
4,Michael Sell,1.0,2.0,98.0,66.0,39.0,14.0,6.0,11.0,1,1

In [ ]:
losers = df[["loser_name", "l_ace", "l_svpt"]].copy()
losers.columns = ["player", "ace", "svpt"]
losers["came_back"] = 0 # Loser cannot comeback
losers["is_winner"] = 0
losers.head(5)

                player   ace   svpt  came_back  is_winner
0         Jeff Tarango   7.0  106.0          0          0
1     Franco Squillari   5.0   74.0          0          0
2  Alberto Berasategui   0.0   56.0          0          0
3        Roger Federer  11.0   70.0          0          0
4       Nicolas Escude   8.0   92.0          0          0

In [124]:
player_stats = pd.concat([winners, losers], axis=0)
player_stats.head(5)

                player   ace  svpt  came_back  is_winner
0           Tommy Haas  18.0  96.0          0          1
1        Juan Balcells   5.0  76.0          0          1
2       Alberto Martin   0.0  55.0          0          1
3  Juan Carlos Ferrero   5.0  53.0          0          1
4         Michael Sell   1.0  98.0          1          1