# Tennis Data Exploration

#### 1. Setup & Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import os

plt.style.use('ggplot')
sns.set_theme(style="whitegrid")
%matplotlib inline

#### 2. Data Loading

In [65]:
RAW_DATA_PATH = "../data/raw_matches.csv"
if not os.path.exists(RAW_DATA_PATH):
  raise FileNotFoundError(f"Run data_retrieval.py first → {RAW_DATA_PATH}")
df = pd.read_csv(RAW_DATA_PATH, low_memory=False)

print(f"Dataset contains {df.shape[0]} matches and {df.shape[1]} features.")
display(df.head())

Dataset contains 79019 matches and 50 features.

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year
0,2000-301,Auckland,Hard,32,A,20000110,1,103163,1.0,NaN,...,39.0,29.0,17.0,4.0,7.0,11.0,1612.0,63.0,595.0,2000
1,2000-301,Auckland,Hard,32,A,20000110,2,102607,NaN,Q,...,25.0,18.0,12.0,3.0,6.0,211.0,157.0,49.0,723.0,2000
2,2000-301,Auckland,Hard,32,A,20000110,3,103252,NaN,NaN,...,20.0,7.0,8.0,7.0,11.0,48.0,726.0,59.0,649.0,2000
3,2000-301,Auckland,Hard,32,A,20000110,4,103507,7.0,NaN,...,29.0,14.0,10.0,6.0,8.0,45.0,768.0,61.0,616.0,2000
4,2000-301,Auckland,Hard,32,A,20000110,5,102103,NaN,Q,...,34.0,18.0,12.0,5.0,9.0,167.0,219.0,34.0,873.0,2000

#### 3. Data Exploration

In [66]:
print(f"Data Shape: {df.shape}", end="\n\n")
print(df.info())

Data Shape: (79019, 50)

<class 'pandas.DataFrame'>
RangeIndex: 79019 entries, 0 to 79018
Data columns (total 50 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   tourney_id          79019 non-null  str
 1   tourney_name        79019 non-null  str
 2   surface             78966 non-null  str
 3   draw_size           79019 non-null  int64
 4   tourney_level       79019 non-null  str
 5   tourney_date        79019 non-null  int64
 6   match_num           79019 non-null  int64
 7   winner_id           79019 non-null  int64
 8   winner_seed         32861 non-null  float64
 9   winner_entry        10153 non-null  str
 10  winner_name         79019 non-null  str
 11  winner_hand         79019 non-null  str
 12  winner_ht           77485 non-null  float64
 13  winner_ioc          79019 non-null  str
 14  winner_age          79007 non-null  float64
 15  loser_id            79019 non-null  int64
 16  loser_seed          18257 non-null  float64
 17  loser_entry         16397 non-null  str
 18  loser_name          79019 non-null  str
 19  loser_hand          79015 non-null  str
 20  loser_ht            75941 non-null  float64
 21  loser_ioc           79019 non-null  str
 22  loser_age           79005 non-null  float64
 23  score               79019 non-null  str
 24  best_of             79019 non-null  int64
 25  round               79019 non-null  str
 26  minutes             70312 non-null  float64
 27  w_ace               72109 non-null  float64
 28  w_df                72109 non-null  float64
 29  w_svpt              72109 non-null  float64
 30  w_1stIn             72109 non-null  float64
 31  w_1stWon            72109 non-null  float64
 32  w_2ndWon            72109 non-null  float64
 33  w_SvGms             72109 non-null  float64
 34  w_bpSaved           72109 non-null  float64
 35  w_bpFaced           72109 non-null  float64
 36  l_ace               72109 non-null  float64
 37  l_df                72109 non-null  float64
 38  l_svpt              72109 non-null  float64
 39  l_1stIn             72109 non-null  float64
 40  l_1stWon            72109 non-null  float64
 41  l_2ndWon            72109 non-null  float64
 42  l_SvGms             72109 non-null  float64
 43  l_bpSaved           72109 non-null  float64
 44  l_bpFaced           72109 non-null  float64
 45  winner_rank         78420 non-null  float64
 46  winner_rank_points  78420 non-null  float64
 47  loser_rank          77466 non-null  float64
 48  loser_rank_points   77466 non-null  float64
 49  year                79019 non-null  int64
dtypes: float64(29), int64(7), str(14)
memory usage: 36.0 MB
None

In [67]:
df.describe()

,draw_size,tourney_date,match_num,winner_id,winner_seed,winner_ht,winner_age,loser_id,loser_seed,loser_ht,...,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points,year
count,79019.000000,7.901900e+04,79019.000000,79019.000000,32861.000000,77485.000000,79007.000000,79019.000000,18257.000000,75941.000000,...,72109.000000,72109.000000,72109.000000,72109.00000,72109.000000,78420.000000,78420.000000,77466.000000,77466.000000,79019.000000
mean,55.533024,2.012267e+07,112.454726,114063.385907,7.460242,186.341795,26.292793,113909.447209,9.014789,185.728263,...,32.552816,14.899167,12.307964,4.76028,8.570276,80.029712,1625.590691,117.532375,988.824813,2012.218125
std,40.407124,7.684293e+04,139.327826,27507.648427,6.873754,7.029637,3.989053,27193.731024,7.455624,6.981291,...,14.359979,7.171966,4.217732,3.26255,4.135239,140.577272,2022.009382,186.471030,1132.567070,7.684083
min,2.000000,2.000010e+07,1.000000,100644.000000,1.000000,3.000000,14.900000,100644.000000,1.000000,3.000000,...,0.000000,0.000000,0.000000,0.00000,0.000000,1.000000,1.000000,1.000000,1.000000,2000.000000
25%,32.000000,2.006010e+07,12.000000,103602.000000,3.000000,183.000000,23.400000,103565.000000,4.000000,183.000000,...,22.000000,10.000000,9.000000,2.00000,6.000000,18.000000,582.000000,36.000000,436.000000,2006.000000
50%,32.000000,2.012042e+07,32.000000,104547.000000,5.000000,185.000000,26.100000,104561.000000,7.000000,185.000000,...,30.000000,14.000000,11.000000,4.00000,8.000000,45.000000,948.000000,68.000000,716.000000,2012.000000
75%,64.000000,2.019020e+07,262.000000,105777.000000,9.000000,190.000000,28.900000,105916.000000,12.000000,190.000000,...,40.000000,19.000000,15.000000,7.00000,11.000000,86.000000,1755.000000,114.000000,1117.000000,2019.000000
max,128.000000,2.026042e+07,1701.000000,214419.000000,35.000000,211.000000,46.000000,214425.000000,35.000000,211.000000,...,284.000000,101.000000,91.000000,27.00000,38.000000,2101.000000,16950.000000,2173.000000,16950.000000,2026.000000

In [ ]:
tourney_level_values = df["tourney_level"].unique().tolist()
surface_values = df["surface"].unique().tolist()
draw_size_values = df["draw_size"].unique().tolist()
round_values = df["round"].unique().tolist()
winner_entry_values = df["winner_entry"].unique().tolist()
winner_hand_values = df["winner_hand"].unique().tolist()

print(f"Unique values for 'TOURNEY_LEVEL': ({len(tourney_level_values)}, {tourney_level_values})")
print(f"Unique values for 'SURFACE': ({len(surface_values)}, {surface_values})")
print(f"Unique values for 'DRAW_SIZE': ({len(draw_size_values)}, {draw_size_values})")
print(f"Unique values for 'ROUND': ({len(round_values)}, {round_values})")
print(f"Unique values for 'WINNER_ENTRY': ({len(winner_entry_values)}, {winner_entry_values})")
print(f"Unique values for 'WINNER_HAND': ({len(winner_hand_values)}, {winner_hand_values})")

Unique values for 'TOURNEY_LEVEL': (6, ['A', 'M', 'G', 'F', 'D', 'O'])
Unique values for 'SURFACE': (5, ['Hard', 'Clay', 'Grass', 'Carpet', nan])
Unique values for 'DRAW_SIZE': (14, [32, 56, 48, 96, 64, 128, 8, 4, 28, 16, 24, 12, 2, 18])
Unique values for 'ROUND': (10, ['R32', 'R16', 'QF', 'SF', 'F', 'R64', 'R128', 'RR', 'BR', 'ER'])
Unique values for 'WINNER_ENTRY': (12, [nan, 'Q', 'WC', 'LL', 'PR', 'SE', 'ALT', 'Alt', 'UP', 'ITF', 'W', 'NG'])
Unique values for 'WINNER_ENTRY': (4, ['R', 'L', 'U', 'A'])

In [69]:
missing = df.isnull().sum().sort_values(ascending=False)
missing[missing > 0]

winner_entry          68866
loser_entry           62622
loser_seed            60762
winner_seed           46158
minutes                8707
l_ace                  6910
l_svpt                 6910
l_1stIn                6910
l_1stWon               6910
l_df                   6910
w_1stIn                6910
w_ace                  6910
w_df                   6910
w_svpt                 6910
w_2ndWon               6910
w_1stWon               6910
w_SvGms                6910
l_2ndWon               6910
l_SvGms                6910
l_bpSaved              6910
l_bpFaced              6910
w_bpSaved              6910
w_bpFaced              6910
loser_ht               3078
loser_rank_points      1553
loser_rank             1553
winner_ht              1534
winner_rank_points      599
winner_rank             599
surface                  53
loser_age                14
winner_age               12
loser_hand                4
dtype: int64

#### 4. Data Cleaning
- 4.1 Removing walkovers, unfinished matches, defaulted matches, missing score matches
- 4.2 Handle missing values
- 4.3 Convert data types

In [ ]:
print(f"Initial: {len(df)} matches in the dataset")
df = df[df["score"].notna()] # Removing matches with no STATS
print(f"Updated: {len(df)} matches left")
df = df[~df["score"].str.contains("RET", na=False)] # Removing matches with RET
print(f"Updated: {len(df)} matches left")
df = df[~df["score"].str.contains("W/O", na=False)] # Removing matches with W/O
print(f"Updated: {len(df)} matches left")
df = df[~df["score"].str.contains("DEF", na=False)] # Removing matches with DEF
print(f"Updated: {len(df)} matches left")

Initial: 76662 matches in the dataset
Updated: 76662 matches left
Updated: 76662 matches left
Updated: 76249 matches left

In [ ]:
# Handle missing numerical column values
num_cols = ["winner_ht", "loser_ht", "minutes"]
df[num_cols] = df[num_cols].fillna(df[num_cols].median())
df[num_cols].isnull().sum()

winner_ht    0
loser_ht     0
minutes      0
dtype: int64

In [74]:
# Handle missing categorical column values
cat_cols_hand = ["loser_hand", "winner_hand"]
cat_cols_entry = ["winner_entry", "loser_entry"]
df[cat_cols_hand] = df[cat_cols_hand].fillna("U")
df["surface"] = df["surface"].fillna("Unknown")
df[cat_cols_entry] = df[cat_cols_entry].fillna("OK")

In [ ]:
# Convert data types
df["tourney_date"] = pd.to_datetime(df["tourney_date"], format="%Y%m%d")